### ISSUE TITLE
nve-badge har litt for mye polstring

### ISSUE THREAD

**Issue by gruble** [NVE/Designsystem#117]
Ser ut som det er litt for mer plass over og under tekst i nve-badge enn i Figma, i hvert fall i middels størrelse:
![image](https://github.com/NVE/Designsystem/assets/71138449/99b4e3c4-377d-4b32-a3f8-973a35245b21)

**Comment by knutnve** [comment]
Status på denne?

**Comment by gruble** [comment]
Jeg synes det ser mer riktig ut nå, hva denker du, @knutnve ?
https://designsystem.nve.no/components/nve-badge.html

**Comment by knutnve** [comment]
Ja bedre, men la merke til large, har annen font?
![Screenshot 2024-08-16 at 14 16 50](https://github.com/user-attachments/assets/dfe2208f-3273-4db6-9e1c-15e4222e8b17)

**Comment by tomapedersen** [comment]
Ser ut til å være en feil i dokumentasjonsfilen, ikke i selve komponenten:
```
<nve-badge size="small">small</nve-badge>
<nve-badge>medium</nve-badge>
<nve-badge size="large ">large</nve-badge>
```
Legg merke til at `large` har et mellomrom etter seg, så størrelsen er derfor `'large '`, men koden sjekker naturligvis etter `'large'`

**Comment by tomapedersen** [comment]
@gruble : Siden du har buggen: Fikser du det, eller skal jeg ta det raskt selv

**Comment by gruble** [comment]
Ta det gjerne du, @tomapedersen. Takk!

**Comment by tomapedersen** [comment]
Tok det inn som PR og merget
