### ISSUE TITLE
transform.js får ikke med seg alle variabler når den tolker dark thema json filter

### ISSUE THREAD

**Issue by amish1188** [NVE/Designsystem#122]
Ser ut at varsom dark og nve dark mangler ganske mange variabler. Jeg får også dette i konsolet etter jeg har kjørt npm run tokenbuild 
`build/css/varsom_dark.css
While building varsom_dark.css, filtered out token references were found; output may be unexpected. Here are the references that are used but not defined in the file
    varsom_brand.000
    varsom_brand.500
    varsom_brand.600
    varsom_blue.950
    varsom_blue.999
    varsom_blue.800
    grey.000
    varsom_blue.100
    grey.500
    varsom_blue.000
    varsom_blue.050
    blue.500
    varsom_blue.600
    varsom_blue.500
    blue.400
    blue.950
    red.950
    yellow.950
    green.950
    grey.800
    blue.999
    red.999
    yellow.999
    green.999
    grey.850
    blue.700
    red.700
    yellow.500
    green.800
    grey.150
    green.150
    yellow.200
    orange.150
    red.050
    grey.200
    green.100
    yellow.100
    orange.050
    red.000
    green.500
    orange.400
    red.500
    grey.950
This is caused when combining a filter and outputReferences.`

**Comment by tomapedersen** [comment]
Det er meningen at det skal være slik. Tanken er at [nve|varsom]_dark.css kun har de variablene som er annerledes. "Grunn-variablene" som f.eks. grey.000 er definert i "vanlig" css, men man inkluderer dark-versjonen for å overskrive (så begge variabel-settene leses inn)

**Comment by amish1188** [comment]
> Det er meningen at det skal være slik. Tanken er at [nve|varsom]_dark.css kun har de variablene som er annerledes. "Grunn-variablene" som f.eks. grey.000 er definert i "vanlig" css, men man inkluderer dark-versjonen for å overskrive (så begge variabel-settene leses inn)

Så du mener at vi skal bruke både varsom.css og varsom_dark.css samtidig siden varsom_dark.css kan mangle noen variablene som vi skal bruke @tomapedersen?

**Comment by tomapedersen** [comment]
Ja, det var slik det var tenkt. *_dark.css bruker en klasse på root for å aktiveres, så man inkluderer begge og toggler klasse for å slå darkmode av/på

**Comment by amish1188** [comment]
okei, takk :). da må vi kanskje skrive i dokumentasjonen at fil med dark variabler må importes under light mode så at den tar presedens og at begge to må selvfølgelig brukes @gruble .
