### ISSUE TITLE
nve-select har max width satt, det må fjernes

### ISSUE THREAD

**Issue by knutnve** [NVE/Designsystem#172]

**Comment by tomapedersen** [comment]
Man kan style det med 
```
nve-select::part(combobox) {
    max-width: 100%;
}
```

Så ikke helt kritisk

**Comment by gruble** [comment]
@NVEJoel, har ikke du løst dette?

**Comment by NVEJoel** [comment]
Såg kommentaren først nå men ja det borde vara fixat med https://github.com/NVE/Designsystem/commit/15603cb77f7774f1006af6a772a23fe513b78904 for 3 veckor sen. @knutnve du får gerna bekræfta att det fungerar.

**Comment by amish1188** [comment]
Jeg testet det i min app, og bekrefter at den fungerer. Lukker saken
