### ISSUE TITLE
nve-input: prefix icon har ikke margin på venstre side

### ISSUE THREAD

**Issue by knutnve** [NVE/Designsystem#173]
![Screenshot 2024-07-05 at 09 15 43](https://github.com/NVE/Designsystem/assets/129265201/b6516e4d-d7b4-44e6-ab62-604c16ed0c6b)

**Comment by knutnve** [comment]
https://www.figma.com/design/0eXhyUrUF7fWi1VaphfpEu/04---%E2%9D%96-Komponenter?node-id=6106-124258&m=dev

**Comment by tomapedersen** [comment]
Marginen der er satt til "var(--sl-input-spacing-large)" som etter det jeg kan se ikke er inkludert i css'en til designsystemet

**Comment by tomapedersen** [comment]
Ser ut til å virke på test-siden, men ikke i faktisk bruk i et annet prosjekt. Jeg er usikker på hvorfor, men det ser ikke ut til at verdiene som settes i css'en brukes.

**Comment by tomapedersen** [comment]
Det er relatert til noe reset-css som blir lagt inn som standard, ikke designsystemet. Fikser og lukker denne
