### ISSUE TITLE
Kunne bytte mellom NVE- og Varsom-tema i test / dokumentasjons-app

### ISSUE THREAD

**Issue by gruble** [NVE/Designsystem#185]
Idag bruker vi Varsom-tema i kjørende kodeeksempler i [designsystem.nve.no](https://designsystem.nve.no).
Det hadde vært kjekt å enkelt kunne bytte mellom NVE- og Varsom-tema, og kanskje også mellom lys og mørk variant av disse.
Hvem tar utfordringen?

**Comment by amish1188** [comment]
[PR her](https://github.com/NVE/Designsystem/pull/187)
