### ISSUE TITLE
Secondary knappen har border? Det må fjernes

### ISSUE THREAD

**Issue by knutnve** [NVE/Designsystem#193]
![Screenshot 2024-08-05 at 15 03 35](https://github.com/user-attachments/assets/991dd9d2-4412-41bd-b209-761b0b39fad6)

Sjekk figma for rikitg oppsett
https://www.figma.com/design/0eXhyUrUF7fWi1VaphfpEu/04---%E2%9D%96-Komponenter?node-id=280-11025&t=k3KBl5jtl69C145t-4

**Comment by knutnve** [comment]
![Screenshot 2024-08-05 at 15 05 27](https://github.com/user-attachments/assets/589bf3b6-2dfb-452e-844b-ae3ed13c8b3d)

**Comment by NVEJoel** [comment]
Skapat en PR om det https://github.com/NVE/Designsystem/pull/194/files 
Ændrat færg på primary også og lagt till min-width efter design.
