### ISSUE TITLE
Button er ikke kvadratisk når du kun viser ikon

### ISSUE THREAD

**Issue by knutnve** [NVE/Designsystem#201]
Button er ikke kvadratisk når du kun viser ikon. Det er et gap mellom prefix - label - suffix selv om de er tomme/blanke.

**Comment by amish1188** [comment]
Jeg laget nve-icon-button [som er reviewet nå](https://github.com/NVE/Designsystem/pull/209). Tror den burde brukes i stedet. Har skrevet om det i nve-button.md og. Tagget deg til å teste og.
