### ISSUE TITLE
nve-switch

### ISSUE THREAD

**Issue by knutnve** [NVE/Designsystem#202]
nve-switch & nve-theme-switcher

KRAV:
- Switch må også støtte ikon grunnet them switcher
- Støtte tekst ved siden av
- Default, disabled, hover, active

https://www.figma.com/design/0eXhyUrUF7fWi1VaphfpEu/04---%E2%9D%96-Komponenter?node-id=4229-83176

Vi bruker denne i Kontroll, Sektoravgift og KBO og trenger å få utviklet denne til DS.  

![image](https://github.com/user-attachments/assets/ad0f6f6d-7028-4420-a84e-77db24878797)

![image](https://github.com/user-attachments/assets/075e5b73-aee9-4706-99f2-2ebc495f14c5)

**Comment by tomapedersen** [comment]
PR: https://github.com/NVE/Designsystem/pull/206

**Comment by tomapedersen** [comment]
Merget inn PR nå
