### ISSUE TITLE
NVE-Chip (Slå sammen chip-tag og chip-filter)

### ISSUE THREAD

**Issue by knutnve** [NVE/Designsystem#203]
Filter chips og filter tag slås sammen i ett og samme komponent.

Spec:
- Finnes i alle alert farger
- Også med valg på emphasized, default og subtle
- Finnes i semibold, regular og uppercase regular
- Størrelse medium og small

- Når det er close icon, må vi ha hover. Enige om å bruke `:has - selector` 

https://www.figma.com/design/0eXhyUrUF7fWi1VaphfpEu/04---%E2%9D%96-Komponenter?node-id=4229-95265&t=ZMz2unC56ngmn24s-4
_________

- [x] Fikser NVE-tag, og gjøre klargjøre for at det kan utvikles
- [x] Tilby ferdig preset på chip filter tag bygget på chip tag
- [ ] Kode komponentet

**Comment by knutnve** [comment]
![image](https://github.com/user-attachments/assets/798f99eb-cd81-4b88-ba11-34988583b1e8)

**Comment by tomapedersen** [comment]
Laget en PR nå: https://github.com/NVE/Designsystem/pull/213
