### ISSUE TITLE
nve-tooltip har feil font, hjørneradius og farge

### ISSUE THREAD

**Issue by gruble** [NVE/Designsystem#219]
Vi må bruke nve-tokens for disse.
@knutnve kan du spesifisere mer?

**Comment by knutnve** [comment]
Enkel jobb:

Tooltip skal ha revered colors. Som vil si fargene flippes, så bg= fg. 

- Endre bg farge til: `neutrals-foreground-primary`
- Endre fg farge til: `neutrals-background-primary`
- `border radius-small`
- `spacing-xsmall `padding sidene og top/bunn. 


Angående oppførsel, er det sånn SL komponentet kun er med pil under i midten?

**Comment by knutnve** [comment]
Skal vi tilby feedback fargen til tooltipen?

**Comment by tomapedersen** [comment]
Kan gjøre det. Dersom jeg skal endre fargene er det ikke en stor sak å legge til variant også

Plassering for pil på tooltip er avhengig av hvor tooltip plasseres og hvor target er. Man kan også sette `placement` for tooltip for å overstyre, se første eksempel på https://shoelace.style/components/tooltip

**Comment by tomapedersen** [comment]
🛈 : Siden vi nå bruker feedback-fargene, så brukes da disse, så punktet med `neutrals-foreground-primary` / `neutrals-background-primary` gjelder ikke, vi bruker variablene av typen `feedback-background-emphasized-neutral`
