### ISSUE TITLE
Kontrastkrav ikke møtt - Feil foreground-farge på emphasized - nve-alert

### ISSUE THREAD

**Issue by knutnve** [NVE/Designsystem#232]
![Screenshot 2024-08-27 at 14 05 57](https://github.com/user-attachments/assets/cb7c9b8d-d360-49e7-911c-f86254ce3b23)
![Screenshot 2024-08-27 at 14 06 12](https://github.com/user-attachments/assets/55c9815b-63d0-4a08-a88f-bc704df90080)

skal være feedback-foreground-emphasized- ....

![Screenshot 2024-08-27 at 14 06 18](https://github.com/user-attachments/assets/ad31d9fc-851a-4644-a2ce-138696df1acc)

**Comment by knutnve** [comment]
Forgrunnfagrene er satt til` feedback-foreground-default`. Skal være `feedback-foreground-emphasized`

**Comment by tomapedersen** [comment]
@knutnve : Sjekk nå

**Comment by knutnve** [comment]
Yes! Takk
