### ISSUE TITLE
NVE Stepper resetter ikke i riktig index posisjon utifra handler moveToStep() 

### ISSUE THREAD

**Issue by khoi-nve** [NVE/Designsystem#233]
![ScreenShot Tool -20240828114712](https://github.com/user-attachments/assets/29975800-3dab-456a-8cea-4f852aaf9a9b)
 
Det er en bug på `nve-stepper` kompontet. 

Når jeg er på `oppsummerings` siden, og bruke en handler som heter `moveToStep()`  ved å trykke på `Endre`  knappen **(A)** og  flytter den til `step 1`, så fungerer det.

![ScreenShot Tool -20240828114813](https://github.com/user-attachments/assets/90079f34-b6d2-4a07-8c00-4741fb9a47de)

men problemet er at ikonene som er markert `checked` blir ikke resettet seg til `unchecked` **(B)**, og i tillegg knappen som står `Send Inn` **(C)** blir ikke resettet til teksten som er da `neste`.

**Comment by NVEJoel** [comment]
Fungerar i senaste versionen så stænger ærendet.
