### ISSUE TITLE
Rette tekst "Source of thruth" på sida "Om designystemet" i introduksjonskapitlet: 

### ISSUE THREAD

**Issue by gruble** [NVE/Designsystem#244]
Jeg fikk denne av Mats:
![image](https://github.com/user-attachments/assets/8028ca1f-742e-4e14-b662-80a321c56983)
som sier "burde det ikke være _single source of truth_"?

**Comment by knutnve** [comment]
Ja enig. Men har endret endel på den PR-en som er conflict på. Trenger hjelp for å løse den. 

Der kan vi også endre til "single source of truth".
