### ISSUE TITLE
nve-menu har ikke egen side og må bygges bedre

### ISSUE THREAD

**Issue by knutnve** [NVE/Designsystem#252]
nve-menu har ikke egen side i designssytem oversikten, så må bygges opp og dokumenteres.

Må også kodes bedre for å støtte søkefunksjonalitet i nve-dropdown-multiple select.

Har heller ikke rolle i kode

**Comment by knutnve** [comment]
@gruble Følger du opp denne

**Comment by gruble** [comment]
Jeg kan fikse en dokumentasjons-/testside.  Foreslår at vi deler opp resten av det som mangler i flere mindre issues.
