### ISSUE TITLE
Førbætra nve-accordion

### ISSUE THREAD

**Issue by NVEJoel** [NVE/Designsystem#306]
Feedback fra Øystein når jeg skapte nve-accordion: 

Når det gjelder å gruppere flere komponenter, synes jeg funksjonen for å sikre at kun en "details-komponent" er utvidet om gangen er såpass viktig at jeg hadde ønsket meg at vi sørget for dette automatisk.
Kunne vi f.eks. hatt en komponent for en gruppe av "details-komponenter" som passet på at kun en komponent inni gruppa kunne ekspanderes om gangen?
Noe a la dette?

<nve-accordion>
  <nve-details summary="første">
  <nve-details summary="andre">
  <nve-details summary="tredje">
</nve-accordion>

**Comment by knutnve** [comment]
1. Skal vi helst ikke legge inn ustylet shoelace komponenter uten styling til våres komponentliste. 
Det er = ikke godkjent kvalitetsikring på design siden. 

2. NVE-accordion varianter:
- **Size** - Small, large
- **Type** - background, border
- **Color**: Neutral, neutral grey, eller transparrent (=kun border)

3. NVE-Accordion items:
- **Top**: Chevron (locked), title (locked), extra text, badge, tag, slot + right side slot
- **Innhold**: Text, slot


![image](https://github.com/user-attachments/assets/cbf909dd-9748-478a-8ccd-a6174c499adb)

![image](https://github.com/user-attachments/assets/77deee2a-1c51-4567-9fed-bdd03339d06c)


https://github.com/user-attachments/assets/d34df28c-0ac1-46d1-99eb-5452710fe39c


Gjerne kom med tilbakemelding, og om vi skal tilpasse navngivning?
