### ISSUE TITLE
nve-select har feil skrifttype

### ISSUE THREAD

**Issue by gruble** [NVE/Designsystem#344]
Se Knuts kommentar her:
https://github.com/NVE/Designsystem/pull/343#issuecomment-2493586787

Ser ut som det er Shoelace-skrifttype på valgene i valglista. Har ikke sjekket hvilken skrifttype det er på valget som er gjort. Sjekk evt. Figma for hvaslags skrifttyper vi skal ha.

**Comment by knutnve** [comment]
Bruker label-small-light

https://www.figma.com/design/0eXhyUrUF7fWi1VaphfpEu/04---%E2%9D%96-Komponenter?node-id=3114-119190&t=E2ir90FWbVswtP2m-4

**Comment by knutnve** [comment]
+ Har vi mulighet til å endre fra shoelace ikon til material cehvron?
