### ISSUE TITLE
NVE-Radio - Design feedback

### ISSUE THREAD

**Issue by knutnve** [NVE/Designsystem#45]
Noen kommentarer

![Frame 336](https://github.com/NVE/Designsystem/assets/129265201/1119dc30-71df-47e8-b956-3c175d9651e5)

_Originally posted by @knutnve in https://github.com/NVE/Designsystem/issues/17#issuecomment-1860689343_

**Comment by Citaborg** [comment]
Jeg har ikke sett så mye på det, men vet ikke hvor enkelt der er å fikse - derfor ble det ikke prioritert. Den svarte "prikken" i shoelace er en svg: 
![image](https://github.com/NVE/Designsystem/assets/3041020/04da6ac0-6c43-4902-820d-2b42d778bef2)

**Comment by Citaborg** [comment]
fixed in #47
