### ISSUE TITLE
Errorstate / validering på radio visualiseres ikke som i design

### ISSUE THREAD

**Issue by Citaborg** [NVE/Designsystem#49]
Skal se slik ut: 
![image](https://github.com/NVE/Designsystem/assets/3041020/1426b59c-6a7d-4ee8-85e0-3e2c8411844a)

**Comment by amish1188** [comment]
den er tatt i (denne PRen)[https://github.com/NVE/Designsystem/pull/80]

**Comment by amish1188** [comment]
den er tatt i [denne PRen](https://github.com/NVE/Designsystem/pull/80)
